/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javathreading;

import org.junit.Test;

<<<<<<< HEAD
import net.putfirstthingsfirst.extendsThreading.App;
=======
import threading.extend.App;
>>>>>>> e533d501c0a93396dfbb54dc25c77dd1b84c7976

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
