/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.putfirstthingsfirst.thread.tests;

import org.junit.Test;
import net.putfirstthingsfirst.thread.*;
import static org.junit.Assert.*;

public class AppTest {
	@Test
	public void testAppHasAGreeting() {
		Greeting classUnderTest = new Greeting();
		assertNotNull("app should have a greeting", classUnderTest.toString());
	}
}
