/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.putfirstthingsfirst.runable_inline;

public class Start {
	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {

		System.out.println("Start Thread A");
		Thread t1 = new Thread(new Runnable() {

			@Override
			public void run() {
				Thread.currentThread().setName("Runable A");
				for (int i = 0; i < 1000; i++) {
					System.out.println(String.format("%s : %s", Thread.currentThread().getName(), i));
					try {
						Thread.sleep(10);
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}
		});
		t1.start();

		System.out.println("Start Thread B");
		Thread t2 = new Thread(new Runnable() {

			@Override
			public void run() {
				Thread.currentThread().setName("Runable B");
				for (int i = 0; i < 1000; i++) {
					System.out.println(String.format("%s : %s", Thread.currentThread().getName(), i));
					try {
						Thread.sleep(10);
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}
		});
		t2.start();
	}
}