/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package implementsRunable;

public class App {
	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {

		System.out.println("Start Thread 1");
		Thread t1 = new Thread(new TaskRunable("Rubable A"));
		t1.start();
		
		System.out.println("Start Thread 2");
		Thread t2 = new Thread(new TaskRunable("Rubable B"));
		t2.start();
	}
}